[package]
name = "pulse-ffi"
version = "0.1.0"
authors = ["Dan Glastonbury <dglastonbury@mozilla.com>"]

[features]
default = ["static-link"]
static-link = []
dynamic-link = []

[dependencies]
libc = "*"
