language: rust
cache: cargo
notifications:
  email:
    on_success: never

script:
  cargo build --target ${TARGET} --features ${FEATURES}

env:
  TARGET=x86_64-unknown-linux-gnu FEATURES=""
  TARGET=x86_64-unknown-linux-gnu FEATURES="pulse-dynamic-link"
  TARGET=i686-unknown-linux-gnu FEATURES=""
  TARGET=i686_64-unknown-linux-gnu FEATURES="pulse-dynamic-link"
rust:
  - 1.15.1
  - nightly

matrix:
  include:
  - env: TARGET=x86_64-unknown-linux-gnu
    addons:
      apt:
        packages:
        - libpulse-dev
  - env: TARGET=i686-unknown-linux-gnu
    addons:
      apt:
        packages:
        - gcc-multilib
        - libpulse-dev:i386
  allow_failures:
  - rust: nightly
