language: rust
cache: cargo
rust:
  - 1.15.1
  - stable
  - beta
  - nightly
os:
  - linux
addons:
  apt:
    packages:
      - gcc-multilib
      - libpulse-dev
env:
  - ARCH=x86_64
  - ARCH=x86_64 CARGOOPTS="--features pulse-dynamic-link"
  - ARCH=i686
  - ARCH=i686 CARGOOPTS="--features pulse-dynamic-link"
notifications:
  email:
    on_success: never
matrix:
  allow_failures:
    -rust: nightly
script: |
  curl -sSL https://raw.githubusercontent.com/djg/travis-rust-matrix/master/test | bash
