language: rust
cache: cargo
notifications:
  email:
    on_success: never
script: >
  cargo test
    --target ${ARCH}-unknown-linux-gnu
    ${FEATURES:+\--features ${FEATURES}}
before_install: >
  if [ ${ARCH} = "i686" ]; then
    rustup target add i686-unknown-linux-gnu;
  fi
rust:
  - 1.15.1
  - stable
  - nightly
addons: &apt_64
  apt:
    packages:
    - libpulse-dev
env:
  # default jobs
  - ARCH=x86_64
  - ARCH=x86_64 FEATURES="pulse-dlopen"
matrix:
  include:
  # Add in 32-bit builds
  - rust: 1.15.1
    env: ARCH=i686
    addons: &apt_32
      apt:
        packages:
        - gcc-multilib
        - libpulse-dev:i386
  - rust: 1.15.1
    env: ARCH=i686 FEATURES="pulse-dlopen"
    addons: *apt_32
  - rust: stable
    env: ARCH=i686
    addons: *apt_32
  - rust: stable
    env: ARCH=i686 FEATURES="pulse-dlopen"
    addons: *apt_32
  - rust: nightly
    env: ARCH=i686
    addons: *apt_32
  - rust: nightly
    env: ARCH=i686 FEATURES="pulse-dlopen"
    addons: *apt_32
  allow_failures:
  - rust: nightly
