language: rust
sudo: false
cache: cargo
rust:
  - stable
os:
  - linux
addons:
  apt:
    packages:
      - &apt_64 [libpulse-dev]
      - &apt_32 [gcc-multilib, "libpulse-dev:i386"]
notifications:
  email:
    on_success: never
script: |
  curl -sSL https://raw.githubusercontent.com/djg/travis-rust-matrix/master/test | bash
matrix:
  allow_failures:
    - rust: nightly
  include:
    - env: ARGH=x86_64
      addons:
        apt:
          packages:
            - *apt_64
    - env: ARGH=x86_64 CARGOOPTS="--features pulse-dynamic-link"
      addons:
        apt:
          packages:
            - *apt_64
    - env: ARGH=i686
      addons:
        apt:
          packages:
            - *apt_32
    - env: ARGH=i686 CARGOOPTS="--features pulse-dynamic-link"
      addons:
        apt:
          packages:
            - *apt_32
