language: rust
dist: trusty
cache: cargo
rust:
  - 1.15.1
  - stable
  - beta
  - nightly
os:
  - linux
env:
  - TARGET=x86_64-unknown-linux-gnu FEATURES="static-link"
  - TARGET=x86_64-unknown-linux-gnu FEATURES="dynamic-link"
  - TARGET=i686-unknown-linux-gnu FEATURES="static-link"
  - TARGET=i686-unknown-linux-gnu FEATURES="dynamic-link"
before_install:
  # Install cross targets which aren't the host architecture.
  - test -n "${TARGET##x86_64*}" && rustup target add ${TARGET}
notifications:
  email:
    on_success: never
matrix:
  allow_failures:
    -rust: nightly
script: |
  cargo test --target ${TARGET} --features ${FEATURES}
