language: rust
sudo: false
cache: cargo
os:
- linux
notifications:
  email:
    on_success: never
script: |
  curl -sSL https://raw.githubusercontent.com/djg/travis-rust-matrix/master/test | bash
matrix:
  exclude:
    - rust: stable
  include:
  - rust: 1.15.1
    env: ARCH=x86_64
    addons: &apt_64
      apt:
        packages:
        - libpulse-dev
  - rust: 1.15.1
    env: ARCH=x86_64 CARGOOPTS="--features pulse-dynamic-link"
    addons: *apt_64
  - rust: 1.15.1
    env: ARCH=i686
    addons: &apt_32
      apt:
        packages:
        - gcc-multilib
        - libpulse-dev:i386
  - rust: 1.15.1
    env: ARCH=i686 CARGOOPTS="--features pulse-dynamic-link"
    addons: *apt_32
  allow_failures:
  - rust: nightly
